### ISSUE TITLE
No alarm being added for Kerbin Dres Transfer

### ISSUE THREAD

**Issue by ghosty141** [meckryl/AlarmClockForKSP2#1]
![KSP2_x64_2024-01-02_18-02-17](https://github.com/meckryl/AlarmClockForKSP2/assets/17564201/440a96b3-052a-4e53-8e7b-424243a21daf)

Clicking Confirm goes back to the alarm page but no alarm has been added.

**Comment by meckryl** [comment]
I just made a bunch of changes to the transfer window planner this morning. I'll upload that version in just a few minutes. The system used to rely on the time that had passed since the start of the game; I can't easily test but I'm pretty sure that the issue you experienced might have been related to that. I now get the position of the planets directly and calculate from there (with more accurate info on their properties in general). Hopefully that will resolve your issue!

**Comment by meckryl** [comment]
Put out the release, let me know once you update if the problem persists

**Comment by ghosty141** [comment]
Just tested it and looks good!
